rules:
  #comparison:
  #JWT:
  comparison:
    type-comparison:
      level: ignore
  missing:
    decision:
      level: ignore
    deny-reasons:
      level: ignore
  naming:
    prefix-underscore:
      level: ignore
  negation:
    not-outside-deny:
      level: ignore
  obsolete: 
    max-n-lines:
      level: ignore
      max-lines: 8
  safety:
    disallow-else:
      level: ignore
    else-if:
      level: ignore
  structure:
    two-decision-clauses:
      level: ignore

  