rules:
  #comparison:
  #JWT:
  missing:
    decision:
      level: warning
    deny-reasons:
      level: warning
  naming:
    prefix-underscore:
      level: warning
  negation:
    not-outside-deny:
      level: warning
  safety:
    disallow-else:
      level: warning
    else-if:
      level: warning
  structure:
    two-decision-clauses:
      level: warning
  style:
    max-n-lines:
      level: warning
      max-lines: 8