rules:
  #comparison:
  #JWT:
  comparison:
    type-comparison:
      level: error
  missing:
    decision:
      level: error
    deny-reasons:
      level: error
  naming:
    prefix-underscore:
      level: error
  negation:
    not-outside-deny:
      level: error
  obsolete: 
    max-n-lines:
      level: error
      max-lines: 8
  safety:
    disallow-else:
      level: error
    else-if:
      level: error
  structure:
    two-decision-clauses:
      level: error

  