rules:
  custom: 
    forbidden-function-call:
      level: error
      forbidden-functions:
        - gt
        - gte
        - lt
        - lte
  comparison:
    type-comparison:
      level: warning
  missing:
    decision:
      level: ignore
    deny-reasons:
      level: ignore
  naming:
    prefix-underscore:
      level: ignore
  negation:
    not-outside-deny:
      level: ignore
  obsolete: 
    max-n-lines:
      level: ignore
      max-lines: 8
  safety:
    disallow-else:
      level: error
    else-if:
      level: error
  structure:
    two-decision-clauses:
      level: ignore

  